//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace documentify.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class documentifyDataEntities : DbContext
    {
        public documentifyDataEntities()
            : base("name=documentifyDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<page> pages { get; set; }
        public virtual DbSet<projet> projets { get; set; }
        public virtual DbSet<section> sections { get; set; }
        public virtual DbSet<sous_section> sous_section { get; set; }
    }
}
