//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace documentify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projet
    {
        public projet()
        {
            this.pages = new HashSet<page>();
        }
    
        public int id_projet { get; set; }
        public string nom { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<page> pages { get; set; }
    }
}
