//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace documentify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class section
    {
        public section()
        {
            this.sous_section = new HashSet<sous_section>();
        }
    
        public int id_section { get; set; }
        public string titre { get; set; }
        public string contenu { get; set; }
        public int ordre { get; set; }
        public int id_page { get; set; }
    
        public virtual page page { get; set; }
        public virtual ICollection<sous_section> sous_section { get; set; }
    }
}
