//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace documentify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sous_section
    {
        public int id_sous_section { get; set; }
        public int id_section { get; set; }
        public string titre { get; set; }
        public string contenu { get; set; }
        public int ordre { get; set; }
    
        public virtual section section { get; set; }
    }
}
